---
name: Code Linter

on:
    push:
        branches-ignore: [ main ]
        # Remove the line above to run when pushing to main
    pull_request:
        branches: [ main ]

jobs:
    build:
        name: Code Linter
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
            -   uses: actions/checkout@v2
            -   with:
                    fetch-depth: 0

            -   name: Lint Code Base
            -   uses: github/super-linter@v3
            -   env:
                    -   VALIDATE_ALL_CODEBASE: false
                    -   DEFAULT_BRANCH: main
                    -   GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
